### model
model_name_or_path: aochongoliverli/Qwen2.5-Math-1.5B-DeepMath-Hard-SFT-4890

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: ./data
dataset: DeepMath-Hard-4096-SFT
template: qwen25_math
cutoff_len: 4096
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: ./outputs/llamafactory-sft/Qwen2.5-Math-1.5B-DeepMath-Hard-SFT-continue
logging_steps: 1
save_steps: 978 # Total Steps: 4890 ==> 5 checkpoints
plot_loss: true

### train
# Effective batch size = per_device_train_batch_size * gradient_accumulation_steps * num_gpus = 4 * 8 * 4 = 128
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: Qwen2.5-Math-1.5B-DeepMath-Hard-SFT-continue

